### PR TITLE
Deploy the documentation to GitHub pages

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@HereAround I took the liberty of merging this as further steps may be needed but this can only be done when. Hope you don't mind

**Comment by HereAround** [comment]
@fingolfin: Thx for the PR and looking into this!

I just looked at https://oscar-system.github.io/JToric.jl/. This is where I believe the documentation should be hosted. This page still returns "page not found". Hence, as you anticipated, further steps may be necessary.

**Comment by fingolfin** [comment]
Docs are now available at https://oscar-system.github.io/JToric.jl/dev/

basically, I had to set a working `DOCUMENTER_KEY ` and matching deploy key by following the instructions at https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh

Then I restarted the CI job, which created the `gh-pages` branch. Finally I pointed GitHub pages at the `gh-pages` branch.

**Comment by HereAround** [comment]
Perfect! Thank you!

**Pull request merged**
